### ISSUE TITLE
Multiple Trigger Handlers per object

### ISSUE THREAD

**Issue by keithmancuso** [kevinohara80/sfdc-trigger-framework#7]
Do you recommend having multiple trigger handlers per object? or do you recommend using one handler per object that in turn calls different methods?  I ask cause the main benefit i would love to be able to use the bypass api for handlers on the same trigger object but not sure that will be respected?

**Comment by kevinohara80** [comment]
IMO, the best practice is one handler per object. Having one handler ensures that you always have complete control over your trigger execution. And yes, your single trigger handler would have a method you can override for each trigger context.

I'm not totally sure I understand your question on the bypass API.

**Comment by CzarScar** [comment]
For now we have an issue that the original code has multiple after update triggers on a object and we just refactor the code to one afterUpdateTriggerhandler and some methods. This works fine when the data is not big. But when the data is large, the code will occurred 'Apex CPU time limit exceed' error. Do you have any test on the time limit difference between the one trigger and multiple triggers?

**Comment by kevinohara80** [comment]
Sorry for the late response. I don't have any benchmarks on 1 vs multiple triggers. My guess is that there is no difference.
