### ISSUE TITLE
a test for OpportunityTrigger.trigger?

### ISSUE THREAD

**Issue by bagus1** [kevinohara80/sfdc-trigger-framework#8]
What would that look like?

**Comment by kevinohara80** [comment]
That really depends on your implementation. You'll want to test CRUD operations and assert that your trigger business logic is handling things properly.

**Comment by bagus1** [comment]
Hmm.. My implementation is just what you had:
```
trigger OpportunityTrigger on Opportunity (
  before insert, before update, before delete, 
  after insert, after update, after delete, after undelete) {
  new OpportunityTriggerHandler().run();
}
```

I have tests for the cruddy stuff in OpportunityTriggerHandler in OpportunityTriggerHandlerTest , but I don't have code that tests this trigger on its own. I basically have a blank test now:

```
public class OpportunityTriggerTest  {
// nada
}

```
I mean I haven't put a ton of thought into how it might be tested and I pretty much moved on, but it'd be nice...
